network:
vendors:
  cloud:
    gcp:
      projects:
        production:
        sandbox:
        staging:
        development:
      computeUrlIds:
        production:
        sandbox:
        staging:
        development:
      dnsZone:
      secretsBuckets:
        production:
        sandbox:
        staging:
        development:
      defaults:
        region:
        memory: 128Mi
        memoryOverrides:
          eventStore: 256Mi
          viewStore: 256Mi
  viewStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol:
  eventStore:
    mongodb:
      users:
        production:
        sandbox:
        staging:
        development:
      hosts:
        production:
        sandbox:
        staging:
        development:
      protocol:
defaults:
  viewStore:
  eventStore:
  cloud:
