version: "3"
services:
  command-handler:
    image: us.gcr.io/${GCP_PROJECT}/${DOMAIN}.${ACTION}:latest
    container_name: command-handler
    ports:
      - "3000:3000"
    depends_on:
      - event-store
    environment:
      PORT: "3000"
      NODE_ENV: local
      NETWORK: local:80
      SERVICE:
      DOMAIN:
      ACTION:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

  event-store:
    image: us.gcr.io/${GCP_PROJECT}/event-store.${DOMAIN}:latest
    container_name: ${DOMAIN}.event-store.${SERVICE}.local
    ports:
      - "80:80"
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE:
      DOMAIN:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER: gcp-staging
      MONGODB_HOST: staging-ggjlv.gcp.mongodb.net

networks:
  default:
    external:
      name: cloudbuild
