version: "3"
services:
  command-handler:
    image: us.gcr.io/${GCP_PROJECT}/${DOMAIN}.${ACTION}:latest
    container_name: command-handler
    ports:
      - "3000:3000"
    depends_on:
      - event-store
    environment:
      PORT: "3000"
      NODE_ENV: staging
      NETWORK:
      SERVICE:
      DOMAIN:
      ID:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
  event-store:
    image: us.gcr.io/${GCP_PROJECT}/event-store.${DOMAIN}:latest
    container_name: ${DOMAIN}.event-store.${SERVICE}.${NETWORK}
    ports:
      - "27017:27017"
    environment:
      PORT: "27017"
      NODE_ENV: staging
      NETWORK:
      SERVICE:
      DOMAIN:
      ID:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

networks:
  default:
    external:
      name: cloudbuild
