version: "3"
services:
  command-handler:
    image: us.gcr.io/${GCP_PROJECT}/${DOMAIN}.${ACTION}:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    depends_on:
      - event-store
    environment:
      PORT: "${CONTAINER_PORT}"
      NODE_ENV: local
      NETWORK:
      SERVICE:
      DOMAIN:
      ACTION:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

  event-store:
    image: us.gcr.io/${GCP_PROJECT}/event-store.${DOMAIN}:latest
    container_name: ${DOMAIN}.event-store.${SERVICE}.local
    ports:
      - "${LOCAL_NETWORK_PORT}:${LOCAL_NETWORK_PORT}"
    environment:
      PORT: "${LOCAL_NETWORK_PORT}"
      NODE_ENV: local
      NETWORK: ${NETWORK}:${LOCAL_NETWORK_PORT}
      SERVICE:
      DOMAIN:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER: gcp-staging
      MONGODB_HOST: staging-ggjlv.gcp.mongodb.net

networks:
  default:
    external:
      name: cloudbuild
