network: sm.network
vendors:
  cloud:
    gcp:
      projects:
        production: core-production-268920
        sandbox: core-sandbox-268920
        staging: core-staging-268920
        development: core-development-268920
      computeIds:
        production:
        sandbox:
        staging:
        development: "3286424246"
      dnsZone: network
      secretsBuckets:
        production: production-secrets-268920
        sandbox: sandbox-secrets-268920
        staging: staging-secrets-268920
        development: development-secrets-268920
      defaults:
        region: us-central1
        memory: 128Mi
        memoryOverrides:
          eventStore: 256Mi
          viewStore: 256Mi
  viewStore:
    mongodb:
      users:
        production: gcp-production
        sandbox: gcp-sandbox
        staging: gcp-staging
      hosts:
        production: production-ggjlv.gcp.mongodb.net
        sandbox: sandbox-ggjlv.gcp.mongodb.net
        staging: staging-ggjlv.gcp.mongodb.net
      protocol: mongodb+srv
  eventStore:
    mongodb:
      users:
        production: gcp-production
        sandbox: gcp-sandbox
        staging: gcp-staging
      hosts:
        production: production-ggjlv.gcp.mongodb.net
        sandbox: sandbox-ggjlv.gcp.mongodb.net
        staging: staging-ggjlv.gcp.mongodb.net
      protocol: mongodb+srv
defaults:
  viewStore: mongodb
  eventStore: mongodb
  cloud: gcp
