#
# This file is required.
# It's URL will be auth.[network]
#

whitelist:
  - "127.0.0.1"
  - "https://${process.env.NETWORK}"

targets:
  - action: issue
    domain: challenge
    context: command-handler
  - action: answer
    domain: challenge
    context: command-handler
  ##unfold later
  - domain: challenge
    context: event-store
  - name: contexts
    domain: person
    context: view-store
  - name: codes
    domain: challenge
    context: view-store
  - name: phones
    domain: person
    context: view-store

dependencies:
  "@sustainers/auth-gateway": "*"
  "@sustainers/gcp-kms": "*"

devDependencies:
  "mocha": "^6.1.4"
  "chai": "^4.2.0"
  "sinon": "^7.3.2"
  "sinon-chai": "^3.3.0"
  "chai-datetime": "^1.5.0"
  "@sustainers/datetime": "*"
  "@sustainers/request": "*"
  "@sustainers/event-store-js": "*"
  "@sustainers/view-store-js": "*"
  "@sustainers/twilio-sms": "*"
  "@sustainers/gcp-secret": "*"
  "@sustainers/uuid": "*"

service: core

#don't change
context: auth-gateway
