version: "3"
services:
  main:
    image: ${CONTAINER_REGISTRY}/${SERVICE}.${CONTEXT}.${OPERATION_HASH}:latest
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - ${PORT}
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      CONTEXT:
      SERVICE:
      DOMAIN:
      ID:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER:
      MONGODB_HOST:

networks:
  default:
    external:
      name: cloudbuild
