#
# This file is required.
# It's URL will be auth.[network]
#

domain: some-domain
service: some-service
context: principle

views:
  - name: some-name
    type: store
    permissions:
      - some-service:some-domain:some-privilege
  - name: some-other-name
    type: composite
    protection: none

whitelist:
  - "127.0.0.1"

devDependencies:
  "mocha": "^7.1.1"
  "chai": "^4.2.0"

#don't change
procedure: view-gateway
