action: issue
domain: challenge

targets:
  - name: phones
    domain: person-account
    context: view-store
  - name: codes
    domain: challenge
    context: view-store
  - domain: challenge
    context: event-store

version: 0

dependencies:
  "@sustainers/command-handler": "*"
  "@sustainers/validator": "*"
  "@sustainers/phone-number": "*"
  "@sustainers/jwt": "*"
  "@sustainers/gcp-kms": "*"
  "@sustainers/duration-consts": "*"
  "@sustainers/uuid": "*"
  "@sustainers/datetime": "*"
  "@sustainers/random-int-of-length": "*"
  "@sustainers/twilio-sms": "*"
  "@sustainers/view-store-js": "*"
  "@sustainers/errors": "*"
  "@sustainers/gcp-secret": "*"

devDependencies:
  "mocha": "^6.1.4"
  "chai": "^4.2.0"
  "sinon": "^7.3.2"
  "sinon-chai": "^3.3.0"
  "chai-datetime": "^1.5.0"
  "@sustainers/datetime": "*"
  "@sustainers/request": "*"
  "@sustainers/event-store-js": "*"
  "@sustainers/uuid": "*"

service: core

#don't change
context: command-handler
