version: "3"
services:
  main:
    image: ${CONTAINER_REGISTRY}/${SERVICE}.${CONTEXT}:latest
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - ${PORT}
    depends_on:
      - event-store
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      CONTEXT:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

  command-handler:
    image: ${STAGING_CONTAINER_REGISTRY}/${SERVICE}.command-handler.${TEST_DOMAIN}.${TEST_ACTION}:latest
    container_name: ${COMMAND_HANDLER_HASH}.${NETWORK}
    ports:
      - ${PORT}
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      CONTEXT: command-handler
      DOMAIN: ${TEST_DOMAIN}
      ACTION: ${TEST_ACTION}
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

  event-store:
    image: ${STAGING_CONTAINER_REGISTRY}/${SERVICE}.event-store.${TEST_DOMAIN}:latest
    container_name: ${EVENT_STORE_HASH}.${NETWORK}
    ports:
      - ${PORT}
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      CONTEXT: event-store
      DOMAIN: ${TEST_DOMAIN}
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER:
      MONGODB_HOST:

networks:
  default:
    external:
      name: cloudbuild
