#
# This file is required.
# It's URL will be auth.[network]
#

domain: some-domain
service: core

jobs:
  - name: some-name
    privileges:
      - some-privilege
  - name: some-other-name
    protection: none

whitelist:
  - "127.0.0.1"

devDependencies:
  "mocha": "^7.1.0"
  "chai": "^4.2.0"

#don't change
procedure: fact-gateway
