version: "3"
services:
  main:
    image: us.gcr.io/smn-core-staging/core.command-gateway.session:latest
    container_name: main
    ports:
      - "80"
    environment:
      PORT: "80"
      NODE_ENV: local
      DOMAIN: session
      NETWORK: local
      CONTEXT: command-gateway
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
    depends_on:
      - session-core
      - answer-challenge-core
      - issue-challenge-core
      - challenge-core
      - permissions-principle-core
      - codes-challenge-core
      - phones-user-core
      - contexts-user-core
      - start-session-core
      - db
  session-core:
    ports:
      &a1
      - "80"
    image: us.gcr.io/smn-core-staging/core.event-store.session:latest
    container_name: 471181726.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: event-store
      DOMAIN: session
  answer-challenge-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.command-handler.challenge.answer:latest
    container_name: 1871338131.local
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      CONTEXT: command-handler
      DOMAIN: challenge
      ACTION: answer
  issue-challenge-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.command-handler.challenge.issue:latest
    container_name: 3286424246.local
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      CONTEXT: command-handler
      DOMAIN: challenge
      ACTION: issue
  challenge-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.event-store.challenge:latest
    container_name: 2984375075.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: event-store
      DOMAIN: challenge
  permissions-principle-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.view-store.principle.permissions:latest
    container_name: 3038792079.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: view-store
      DOMAIN: principle
      NAME: permissions
  codes-challenge-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.view-store.challenge.codes:latest
    container_name: 540920284.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: view-store
      DOMAIN: challenge
      NAME: codes
  phones-user-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.view-store.user.phones:latest
    container_name: 4108474047.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: view-store
      DOMAIN: user
      NAME: phones
  contexts-user-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.view-store.user.contexts:latest
    container_name: 796671388.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: view-store
      DOMAIN: user
      NAME: contexts
  start-session-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.command-handler.session.start:latest
    container_name: 2901643442.local
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      CONTEXT: command-handler
      DOMAIN: session
      ACTION: start
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_INITDB_DATABASE: admin
      MONGODB_DATABASE: testing
      MONGODB_USER: tester
      MONGODB_USER_PASSWORD: password
    volumes:
      - ./mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
    ports:
      - 27017:27017
networks:
  default:
    external:
      name: cloudbuild
