version: "3"
services:
  main:
    image: us.gcr.io/smn-core-staging/core.command-gateway.some-domain:latest
    container_name: main
    ports:
      - "80"
    environment:
      PORT: "80"
      NODE_ENV: local
      DOMAIN: some-domain
      NETWORK: local
      CONTEXT: command-gateway
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
    depends_on:
      - some-action-some-domain-core
      - some-other-action-some-domain-core
      - some-domain-core
      - db
  some-action-some-domain-core:
    ports:
      &a1
      - "80"
    image: us.gcr.io/smn-core-staging/core.command-handler.some-domain.some-action:latest
    container_name: 536819634.local
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      CONTEXT: command-handler
      DOMAIN: some-domain
      ACTION: some-action
  some-other-action-some-domain-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.command-handler.some-domain.some-other-action:latest
    container_name: 2068976027.local
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      CONTEXT: command-handler
      DOMAIN: some-domain
      ACTION: some-other-action
  some-domain-core:
    ports: *a1
    image: us.gcr.io/smn-core-staging/core.event-store.some-domain:latest
    container_name: 1922601977.local
    depends_on:
      - db
    environment:
      PORT: "80"
      NODE_ENV: local
      NETWORK: local
      SERVICE: core
      GCP_PROJECT: smn-core-staging
      GCP_REGION: us-central1
      GCP_SECRET_BUCKET: smn-staging-secrets
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION: global
      GCP_KMS_SECRET_BUCKET_KEY_RING: secret-bucket
      MONGODB_USER: tester
      MONGODB_HOST: mongodb
      MONGODB_USER_PASSWORD: password
      MONGODB_PROTOCOL: mongodb
      MONGODB_DATABASE: testing
      CONTEXT: event-store
      DOMAIN: some-domain
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: password
      MONGODB_INITDB_DATABASE: admin
      MONGODB_DATABASE: testing
      MONGODB_USER: tester
      MONGODB_USER_PASSWORD: password
    volumes:
      - ./mongodb-init.sh:/docker-entrypoint-initdb.d/mongodb-init.sh:ro
    ports:
      - 27017:27017
networks:
  default:
    external:
      name: cloudbuild
