version: "3"
services:
  event-store:
    image: ${CONTAINER_REGISTRY}/event-store.${DOMAIN}:latest
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - ${PORT}
    environment:
      PORT: ${PORT}
      NODE_ENV:
      NETWORK:
      SERVICE:
      DOMAIN:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER:
      MONGODB_HOST:

networks:
  default:
    external:
      name: cloudbuild
