steps:
  - name: node:10.16.0
    entrypoint: yarn
    args:
      - install
  - name: node:10.16.0
    entrypoint: yarn
    args:
      - test:unit
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us.gcr.io/smn-core-staging/core.view-store.some-domain.some-name
      - .
  - name: docker/compose:1.15.0
    args:
      - up
      - -d
  - name: docker/compose:1.15.0
    args:
      - ps
  - name: node:10.16.0
    entrypoint: yarn
    args:
      - test:integration
  - name: docker/compose:1.15.0
    args:
      - logs
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us.gcr.io/smn-core-staging/core.view-store.some-domain.some-name
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - run
      - deploy
      - us-central1-core-view-store-some-doma-3048267558
      - --image=us.gcr.io/smn-core-staging/core.view-store.some-domain.some-name
      - --platform=managed
      - --memory=128Mi
      - --project=smn-core-staging
      - --region=us-central1
      - --set-env-vars=NODE_ENV=staging,NETWORK=us-central1.staging.sm.network,SERVICE=core,CONTEXT=view-store,GCP_PROJECT=smn-core-staging,GCP_REGION=us-central1,GCP_SECRET_BUCKET=smn-secrets-staging-secrets,GCP_KMS_SECRET_BUCKET_KEY_LOCATION=global,GCP_KMS_SECRET_BUCKET_KEY_RING=secret-bucket,DOMAIN=some-domain,NAME=some-name,MONGODB_DATABASE=view-store,MONGODB_USER=gcp-staging,MONGODB_HOST=staging-ggjlv.gcp.mongodb.net,MONGODB_PROTOCOL=mongodb+srv
      - --labels=service=core,context=view-store,domain=some-domain,name=some-name,hash=3048267558
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - dns
      - record-sets
      - transaction
      - start
      - --zone=network
      - --project=smn-core
  - name: gcr.io/cloud-builders/gcloud
    args:
      - beta
      - dns
      - record-sets
      - transaction
      - add
      - ghs.googlehosted.com.
      - --name=3048267558.us-central1.staging.sm.network
      - --zone=network
      - --type=CNAME
      - --ttl=86400
      - --project=smn-core
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud beta dns record-sets transaction execute --zone=network
        --project=smn-core || exit 0
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud beta dns record-sets transaction abort --zone=network
        --project=smn-core || exit 0
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - gcloud beta run domain-mappings create --platform=managed
        --service=us-central1-core-view-store-some-doma-3048267558
        --domain=3048267558.us-central1.staging.sm.network
        --project=smn-core-staging --region=us-central1 || exit 0
