version: "3"
services:
  main:
    image: ${CONTAINER_REGISTRY}/${SERVICE}.${CONTEXT}.${DOMAIN}.did-${ACTION}.${NAME}:latest
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - ${PORT}
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      CONTEXT:
      DOMAIN:
      ACTION:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

networks:
  default:
    external:
      name: cloudbuild
