version: "3"
services:
  main:
    image: ${CONTAINER_REGISTRY}/${TARGET}.${DOMAIN}.did-${ACTION}:latest
    container_name: ${MAIN_CONTAINER_NAME}
    ports:
      - ${PORT}
    depends_on:
      - view-store
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      DOMAIN:
      ACTION:
      TARGET_ID:
      TARGET_DOMAIN:
      TARGET_CONTEXT:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:

  view-store:
    image: ${CONTAINER_REGISTRY}/view-store.${TARGET}:latest
    container_name: ${DOMAIN}.view-store.${SERVICE}.${NETWORK}
    ports:
      - ${PORT}
    environment:
      PORT:
      NODE_ENV:
      NETWORK:
      SERVICE:
      DOMAIN:
      TARGET_ID:
      TARGET_DOMAIN:
      TARGET_CONTEXT:
      GCP_PROJECT:
      GCP_REGION:
      GCP_SECRET_BUCKET:
      GCP_KMS_SECRET_BUCKET_KEY_LOCATION:
      GCP_KMS_SECRET_BUCKET_KEY_RING:
      MONGODB_USER:
      MONGODB_HOST:

networks:
  default:
    external:
      name: cloudbuild
